name: CI Joomla Framework

on:
    push:
    pull_request:
    schedule:
        - cron: 15 2 * * 1

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    tests-unit-mariadb:
        name: Run Unit tests on MariaDB
        runs-on: ubuntu-latest
        container: joomlaprojects/docker-images:php${{ matrix.php_version }}
        strategy:
            matrix:
                php_version: ['8.3', '8.4', '8.5']
                db_version: ['10.4', '10.6', '10.11', '11.4', '11.8', '12.3']
        steps:
            - uses: actions/checkout@v6
            - name: Run Unit tests
              run: |
                  git config --global --add safe.directory $GITHUB_WORKSPACE
                  composer update
                  ./vendor/bin/phpunit --configuration phpunit.mariadb.xml.dist --display-all-issues
        services:
            mariadb:
                image: mariadb:${{ matrix.db_version }}
                env:
                    MARIADB_USER: joomla_ut
                    MARIADB_PASSWORD: joomla_ut
                    MARIADB_ROOT_PASSWORD: joomla_ut
                    MARIADB_DATABASE: joomla_ut
                options: >-
                    --health-cmd="healthcheck.sh --connect --innodb_initialized"
