name: CI Joomla Framework

on:
    push:
    pull_request:
    schedule:
        - cron: 15 2 * * 1

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    tests-unit-postgres:
        name: Run Unit tests on PostgreSQL
        runs-on: ubuntu-latest
        container: joomlaprojects/docker-images:php${{ matrix.php_version }}
        strategy:
            matrix:
                php_version: ['8.3', '8.4', '8.5']
                db_version: ['10', '12', '18']
        steps:
            - uses: actions/checkout@v6
            - name: Run Unit tests
              run: |
                  git config --global --add safe.directory $GITHUB_WORKSPACE
                  composer update
                  ./vendor/bin/phpunit --configuration phpunit.pgsql.xml.dist --display-all-issues
        services:
            postgres:
                image: postgres:${{ matrix.db_version }}-alpine
                env:
                    POSTGRES_USER: joomla_ut
                    POSTGRES_PASSWORD: joomla_ut
                    POSTGRES_DB: joomla_ut
                options: >-
                    --health-cmd="pg_isready -d joomla_ut"
