name: CI Joomla Framework

on:
    push:
    pull_request:
    schedule:
        - cron: 15 2 * * 1

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    tests-unit-mysql:
        name: Run Unit tests on MySQL
        runs-on: ubuntu-latest
        container: joomlaprojects/docker-images:php${{ matrix.php_version }}
        strategy:
            matrix:
                php_version: ['8.3', '8.4', '8.5']
                db_engine: ['mysql', 'mysqli']
                db_version: ['5.7', '8.0', '9']
        steps:
            - uses: actions/checkout@v6
            - name: Run Unit tests
              run: |
                  git config --global --add safe.directory $GITHUB_WORKSPACE
                  composer update
                  ./vendor/bin/phpunit --configuration phpunit.${{ matrix.db_engine }}.xml.dist --display-all-issues
        services:
            mysql:
                image: mysql:${{ matrix.db_version }}
                env:
                    MYSQL_USER: joomla_ut
                    MYSQL_PASSWORD: joomla_ut
                    MYSQL_ROOT_PASSWORD: joomla_ut
                    MYSQL_DATABASE: joomla_ut
